version: "3.8"

services:

  apigateway:
    container_name: forum_learning-apigateway
    build: ./api-gateway/
    ports:
      - "8080:8080"
    environment: 
      - GIN_MODE=release
  
  authentication:
    container_name: forum_learning-authentication
    build: ./authentication/
    environment: 
      - GIN_MODE=release
      - ORACLESQL_HOST=localhost
      - ORACLESQL_PORT=1521
      - ORACLESQL_USER=user
      - ORACLESQL_PASSWORD=password
      - ORACLESQL_DB=forum_learning
  
  authorization:
    container_name: forum_learning-authorization
    build: ./authorization/
    environment: 
      - GIN_MODE=release
      - ORACLESQL_HOST=localhost
      - ORACLESQL_PORT=1521
      - ORACLESQL_USER=user
      - ORACLESQL_PASSWORD=password
      - ORACLESQL_DB=forum_learning
  
  account_manager:
    container_name: forum_learning-account_manager
    build: ./account_manager/
    environment: 
      - GIN_MODE=release
      - ORACLESQL_HOST=localhost
      - ORACLESQL_PORT=1521
      - ORACLESQL_USER=user
      - ORACLESQL_PASSWORD=password
      - ORACLESQL_DB=forum_learning