version: "3.8"

volumes:
  forumlearning-mongodbdata:
  forumlearning-mysqldata:

services:

  apigateway_internal_database:
    container_name: apigateway_internal_database
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: forumlearning123
    volumes:
      - forumlearning-mongodbdata:/data/db
  
  mysqldb:
    restart: always
    image: mysql
    hostname: mysqldb

    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_DATABASE: forum_learning
      MYSQL_USER: forum_learning
      MYSQL_PASSWORD: forum_learning_123
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - forumlearning-mysqldata:/var/lib/mysql
      - ./mysqldump-folder/schema.sql:/docker-entrypoint-initdb.d/1.sql

    ports:
      - "3306:3306"

  # apigateway:
  #   container_name: forum_learning-apigateway
  #   build: ./api-gateway/
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   environment: 
  #     - GIN_MODE=release
  #     - MONGODB_HOST=apigateway_internal_database
  #     - MONGODB_PORT=27017
  #     - MONGOBD_USER=root
  #     - MONGODB_PASSWORD=forumlearning123
  #     - MONGOBD_AUTH_SRC=admin
  
  # authentication:
  #   container_name: forum_learning-authentication
  #   build: ./authentication/
  #   restart: always
  #   environment: 
  #     - GIN_MODE=release
  #     - ORACLESQL_HOST=localhost
  #     - ORACLESQL_PORT=1521
  #     - ORACLESQL_USER=user
  #     - ORACLESQL_PASSWORD=password
  #     - ORACLESQL_DB=forum_learning
  
  # authorization:
  #   container_name: forum_learning-authorization
  #   build: ./authorization/
  #   restart: always
  #   environment: 
  #     - GIN_MODE=release
  #     - ORACLESQL_HOST=localhost
  #     - ORACLESQL_PORT=1521
  #     - ORACLESQL_USER=user
  #     - ORACLESQL_PASSWORD=password
  #     - ORACLESQL_DB=forum_learning
  
  # account_manager:
  #   container_name: forum_learning-account_manager
  #   build: ./account_manager/
  #   restart: always
  #   environment: 
  #     - GIN_MODE=release
  #     - ORACLESQL_HOST=localhost
  #     - ORACLESQL_PORT=1521
  #     - ORACLESQL_USER=user
  #     - ORACLESQL_PASSWORD=password
  #     - ORACLESQL_DB=forum_learning