version: "3.8"

volumes:
  forumlearning-mongodbdata:
  forumlearning-mysqldata:

services:

  # apigateway_internal_database:
  #   container_name: apigateway_internal_database
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - "27018:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: forumlearning123
  #   volumes:
  #     - forumlearning-mongodbdata:/data/db
  
  mysqldb:
    restart: always
    image: mysql
    container_name: mysqldb

    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4

    environment:
      MYSQL_DATABASE: forum_learning
      MYSQL_USER: forum_learning
      MYSQL_PASSWORD: forum_learning_123
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - forumlearning-mysqldata:/var/lib/mysql
      - ./mysqldump-folder/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysqldump-folder/test_data.sql:/docker-entrypoint-initdb.d/2.sql

  #   ports:
  #     - "3306:3306"

  # apigateway:
  #   container_name: forum_learning-apigateway
  #   build: ./api-gateway/
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   environment: 
  #     - GIN_MODE=release
  #     - MONGODB_HOST=apigateway_internal_database
  #     - MONGODB_PORT=27017
  #     - MONGOBD_USER=root
  #     - MONGODB_PASSWORD=forumlearning123
  #     - MONGOBD_AUTH_SRC=admin
  
  identity:
    container_name: forum_learning-indentity
    build: ./identity/
    restart: always
    environment: 
      - GIN_MODE=debug
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=forum_learning
      - MYSQL_PASSWORD=forum_learning_123
      - MYSQL_DATABASE=forum_learning
    ports:
      - "8081:8080"
    depends_on: 
      - mysqldb
  
  # account_manager:
  #   container_name: forum_learning-account_manager
  #   build: ./account_manager/
  #   restart: always
  #   environment: 
  #     - GIN_MODE=release
  #     - ORACLESQL_HOST=localhost
  #     - ORACLESQL_PORT=1521
  #     - ORACLESQL_USER=user
  #     - ORACLESQL_PASSWORD=password
  #     - ORACLESQL_DB=forum_learning

  # post:
  #   container_name: forum_learning-post
  #   build: ./post/
  #   restart: always
  #   command: "php artisan serve --host=0.0.0.0 --port=8000"
  #   environment: 
  #     - APP_NAME=forum_learning-post
  #     - APP_ENV=local
  #     - APP_KEY=
  #     - APP_DEBUG=true
  #     - APP_URL=http://localhost:8000
  #     - DB_CONNECTION=mysql
  #     - DB_HOST=db
  #     - DB_PORT=3306
  #     - DB_DATABASE=forum_learning
  #     - DB_USERNAME=forum_learning
  #     - DB_PASSWORD=forum_learning_123
  #   ports:
  #     - 8082:8000
      
  # front-end_client:
  #   container_name: forum_learning-front_end_client
  #   build: ./front-end_client
  #   restart: always
  #   ports:
  #     - "80:80"